data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://raw.githubusercontent.com/nhut-nam/ChatBoxSystem/main/data/raw/chat_data.csv"
  local_data_file: artifacts/data_ingestion/chat_data.csv